vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        carousels:
            uri_prefix: /images/carousels
            upload_destination: '%kernel.project_dir%/public/images/carousels'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        book-pages:
            uri_prefix: /images/book-pages
            upload_destination: '%kernel.project_dir%/public/images/book-pages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        books:
            uri_prefix: /images/books
            upload_destination: '%kernel.project_dir%/public/images/books'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        authors:
            uri_prefix: /images/authors
            upload_destination: '%kernel.project_dir%/public/images/authors'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        avatars:
            uri_prefix: /images/avatars
            upload_destination: '%kernel.project_dir%/public/images/avatars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            